#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  liftDistance,   sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  conveyorQuad,   sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  flQuad,         sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  frQuad,         sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  brQuad,         sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  blQuad,         sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           scissorLeft2,  tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port4,           backLeft,      tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port5,           backRight,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port6,           scissorLeft,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           scissorRight,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           conveyor,      tmotorVex393_MC29, openLoop, encoderPort, dgtl3)
#pragma config(Motor,  port10,          scissorRight2, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int Lift(int liftTarget, int threshold, int speed);
void SetDriveMotors(int fl, int fr, int bl, int br);
void ResetMotorEncoders();
void SetLiftSpeed(int speed);
task MoveConveyor();

//drive wheels ===14 TICKS PER CM===

task main(){
	ResetMotorEncoders();
	nMotorEncoder[conveyor] = 0;

	SetDriveMotors(-75,75,75,-75);
	while(nMotorEncoder[frontLeft]>(-5*14)){}
	SetDriveMotors(75,-75,-75,75);
	ResetMotorEncoders();
	while(nMotorEncoder[frontLeft]<(5*14)){}
	SetDriveMotors(-10,10,10,-10);
	wait1Msec(100);
	SetDriveMotors(75,75,75,75);
	ResetMotorEncoders();
	while(nMotorEncoder[frontLeft]<(45.5*14)){}
	SetDriveMotors(-10,-10,-10,-10);
	wait1Msec(100);
	SetDriveMotors(0,0,0,0);
	motor[conveyor] = -127;
	while(nMotorEncoder[conveyor]<300){}
	motor[conveyor] = 0;
	SetDriveMotors(-75,75,-75,75);
	ResetMotorEncoders();
	while(nMotorEncoder[frontLeft]>-1300){}
	SetDriveMotors(10,-10,10,-10);
	wait1Msec(100);
	SetDriveMotors(75,75,75,75);
	ResetMotorEncoders();
	while(nMotorEncoder[frontLeft]<(20*14)){}
	SetDriveMotors(-10,-10,-10,-10);
	wait1Msec(100);
	SetDriveMotors(0,0,0,0);
	motor[conveyor] = 127;
	while(nMotorEncoder[conveyor]>0){}
	motor[conveyor] = 0;
}

///////////////////////
//FUNCTIONS AND TASKS//
///////////////////////

int Lift(int liftTarget, int threshold, int speed){ //move lift to within [threshold] of [liftTarget] in cm at speed [speed]
	while(SensorValue(liftDistance)<liftTarget-threshold || SensorValue(liftDistance)>liftTarget+threshold){
		if (SensorValue(liftDistance)<liftTarget-threshold) {
			SetLiftSpeed(-speed);
			} else if (SensorValue(liftDistance)>liftTarget+threshold) {
			SetLiftSpeed(speed);
		}
	}
	SetLiftSpeed(0);
	wait1Msec(100);
	return 0;
}

void SetDriveMotors(int fl, int fr, int bl, int br) //set speeds of all 4 motors
{
	motor[frontLeft] = fl;
	motor[frontRight] = fr;
	motor[backLeft] = bl;
	motor[backRight] = br;
}

void SetLiftSpeed(int speed) //consolidate all lift motor commands to one function
{
	motor[scissorLeft] = speed;
	motor[scissorRight] = speed;
	motor[scissorLeft2] = speed;
	motor[scissorRight2] = speed;
}

void ResetMotorEncoders() //reset drive motor encoders
{
	nMotorEncoder[frontLeft] = 0;
	nMotorEncoder[frontRight] = 0;
	nMotorEncoder[backLeft] = 0;
	nMotorEncoder[backRight] = 0;
}

task MoveConveyor() //autonomous conveyor handler
{
	SensorValue[conveyorQuad] = 0;
	motor[conveyor] = -127;
	while(SensorValue(conveyorQuad)<160){}
	motor[conveyor] = 127;
	while(SensorValue(conveyorQuad)>-600){}
	motor[conveyor] = 0;
}
